spring.application.name=url-shortner



spring.datasource.url=jdbc:postgresql://localhost:5432/url_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update


jwt.secret=e967c8ba5890a202ba7e1c6973fdc1c6f4e380f73714637bedfe437291a5ee96c56c95a3
jwt.expiration=172800000