spring.application.name=url-shortner



spring.datasource.url=jdbc:postgresql://localhost:5432/url_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update


jwt.secret=${JWT_SECRET}
jwt.expiration=172800000

