server.port=8090
spring.application.name=url-shortner



spring.datasource.url=${DB_URI}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Explicitly set the database platform/dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


app.jwt-secret=${JWT_SECRET}
jwt.expiration=172800000
#app.cors.front-end-url=http://localhost:5173
app.cors.front-end-url=${FRONTEND_URL}



